#!/bin/bash
# このshを任意の場所に配置して、core.hooksPathに設定すると全体で利用できます。
# e.g. /usr/local/etc/git-hooks/ にこのスクリプトを配置した場合
# git config --global core.hooksPath /usr/local/etc/git-hooks/

out=$1
cat $out
function message() {
  mv $out $out.tmp
  cat <<EOS > $out
$1#`git branch | grep "*" | awk '{print $2}' | grep -o -e '[0-9]\+'`
EOS
  cat $out.tmp >> $out
}

str=$(cat <<-EOS
🐛 :bug: バグ修正
🔥 :fire: ファイル・機能の削除
✨ :sparkles: 機能追加
♻️ :recycle: リファクタリング
✏️ :pencil2: typo
🎨 :art: 構造の変更
📝;:memo: READMEなどdocs更新
💚 :green_heart: テストやCIの修正・改善
✅ :white_check_mark: テスト追加時
👕 :shirt: Lintエラーの修正やコードスタイルの修正
🔧 :wrench: 設定ファイルの修正、環境変数の追加・修正
⬆️ :arrow_up: 依存パッケージのupgrade
⬇️ :arrow_down: 依存パッケージのdowngrade
➖ :heavy_minus_sign: 依存パッケージの削除
➕ :heavy_plus_sign: 依存パッケージ追加
🚧 :construction: WIP
🚀 :rocket: パフォーマンス改善
🙈 :see_no_evil: .gitignoreのadd/update
🐭 :mouse: add/update .editorconfig
🎉 :tada: Initial Commit
EOS
)
type=$(echo "$str" | peco | awk 'match($0, /(:.*:)/) {print substr($0, RSTART, RLENGTH)}')
message "$type "
